# Generated by Django 2.2.1 on 2019-05-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='Memory',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='Score',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='Time',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
