# Generated by Django 2.2.1 on 2019-05-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20190506_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='Problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='problems.Problem'),
        ),
    ]
